name: Test

jobs:
    test-dak:
        runs-on: ubuntu-latest
        steps:
            - run:
                make test-dak -j

    test-bp:
        runs-on: ubuntu-latest
        steps:
            - run:
                make test-bp -j

